services:
  - name: telegram-bot-service
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PORT
        value: "10000"
